### ISSUE TITLE
Verify external databases actually work

### ISSUE THREAD

**Issue by TinFoilFox** [samfry13/clippy#5]
The app is set up to handle database connections from a file or an external database. We should probably check if external databases actually work and add documentation in the README.md

**Comment by samfry13** [comment]
Looks like this will likely not be able to be supported for the time being. You cannot dynamically swap out the DB Provider in Prisma at runtime, as the generated code is different depending on the provider. Prisma is looking at other solutions right now, but in the meantime, we have to stick with SQLite

[Source](https://github.com/prisma/prisma/issues/3834)
