### ISSUE TITLE
Admin/moderation tools

### ISSUE THREAD

**Issue by TinFoilFox** [samfry13/clippy#6]
There should probably be some way of moderating the app in the case of bad actors.

This could include things like:
- Ability to purge a user account and all of their data
- Banning a user's email
- Ban and purge combo
- Suspending a user, preventing uploads but not deleting videos
- Deleting a single video
- Renaming a video

**Comment by TinFoilFox** [comment]
![Admin_Panel_Mockup](https://user-images.githubusercontent.com/15332259/190915201-60e88777-8077-4acd-9a1b-8ee284086260.png)
Putting the mock up we talked about so I don't forget.

The admin panel should also probably be on a whitelist which could be a ENV variable.

**Comment by samfry13** [comment]
I have enough tools to do these things now. Closing.
